import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F6FA',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#666',
  },
  scroll: {
    paddingHorizontal: Math.min(width * 0.05, 20),
    paddingTop: 16,
    paddingBottom: 24,
  },
  profileWrapper: {
    alignItems: 'center',
    marginBottom: 24,
  },
  profileContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: '#372643',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: '#E8EAF6',
  },
  profileImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  cameraContainer: {
    position: 'absolute',
    bottom: 0,
    right: width < 360 ? '32%' : '36%',
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 8,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    borderWidth: 2,
    borderColor: '#372643',
  },
  sectionTitle: {
    color: '#372643',
    marginTop: 20,
    marginBottom: 12,
    fontSize: 16,
    fontWeight: '700',
    borderBottomWidth: 2,
    borderBottomColor: '#372643',
    paddingBottom: 6,
  },
  section: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  label: {
    color: '#333',
    fontSize: 13,
    marginTop: 12,
    marginBottom: 6,
    fontWeight: '600',
  },
  inputField: {
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#333',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  readOnlyContainer: {
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D0D0D0',
  },
  readOnlyText: {
    fontSize: 14,
    color: '#555',
    fontWeight: '500',
    flex: 1,
  },
  checkboxContainer: {
    marginTop: 8,
  },
  checkboxGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 4,
  },
  halfWidth: {
    width: '50%',
  },
  checked: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: '#372643',
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unchecked: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#372643',
    marginRight: 10,
  },
  checkboxLabel: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  bioInput: {
    height: 100,
    paddingTop: 12,
  },
  charCount: {
    alignSelf: 'flex-end',
    color: '#999',
    fontSize: 11,
    marginTop: 4,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#FFF',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#372643',
  },
  cancelText: {
    color: '#372643',
    fontSize: 15,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    backgroundColor: '#372643',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#372643',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  saveButtonDisabled: {
    backgroundColor: '#9CA3AF',
    opacity: 0.7,
  },
  saveText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
});