import { StyleSheet,StatusBar, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  videoContainer: { flex: 1 },
  fullScreenVideo: { flex: 1 },
  splitScreen: { flex: 1, flexDirection: 'column' },
  videoHalf: { flex: 1, backgroundColor: '#222', borderBottomWidth: 1, borderColor: '#333' },
  fullVideo: { flex: 1 },
  noVideo: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  noVideoText: { color: '#888', marginTop: 10 },
  // ✅ FIXED: Added dynamic top padding for Status Bar
  topBar: { 
    position: 'absolute', 
    top: Platform.OS === 'android' ? (StatusBar.currentHeight || 24) + 10 : 55, // 55 covers iOS Notch/Dynamic Island
    left: 10, 
    right: 10, 
    flexDirection: 'row', 
    alignItems: 'center', 
    zIndex: 10 
  },
  liveTag: { backgroundColor: '#D32F2F', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, marginRight: 10 },
  liveText: { color: '#FFF', fontSize: 12, fontWeight: 'bold' },
  viewersTag: { backgroundColor: 'rgba(0,0,0,0.5)', flexDirection: 'row', padding: 6, borderRadius: 4, alignItems: 'center' },
  viewerText: { color: '#FFF', marginLeft: 6, fontSize: 12 },
  closeBtn: { backgroundColor: 'rgba(0,0,0,0.5)', padding: 8, borderRadius: 20 },
 callCard: { 
    position: 'absolute', 
    top: Platform.OS === 'android' ? (StatusBar.currentHeight || 24) + 60 : 110, // Pushed down
    left: 10, 
    right: 10, 
    backgroundColor: 'rgba(255,255,255,0.95)', 
    borderRadius: 12, 
    overflow: 'hidden', 
    zIndex: 5 
  },
  callCardContent: { flexDirection: 'row', padding: 10, alignItems: 'center' },
  callAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#673AB7', justifyContent: 'center', alignItems: 'center' },
  callAvatarText: { color: '#FFF', fontWeight: 'bold', fontSize: 18 },
  callUser: { color: '#000', fontWeight: 'bold', fontSize: 14 },
  callType: { color: '#666', fontSize: 12 },
  timerBadge: { backgroundColor: '#E8F5E9', padding: 6, borderRadius: 6, flexDirection: 'row', alignItems: 'center' },
  redDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'red', marginRight: 6 },
  timerText: { color: 'green', fontWeight: 'bold', fontSize: 12 },
  endCallBar: { backgroundColor: '#D32F2F', padding: 8, alignItems: 'center' },
  endCallText: { color: '#FFF', fontWeight: 'bold', fontSize: 12 },
  chatArea: { position: 'absolute', bottom: 80, left: 10, right: 10, height: 200, justifyContent: 'flex-end' },
  chatBubble: { backgroundColor: 'rgba(0,0,0,0.6)', padding: 8, borderRadius: 8, alignSelf: 'flex-start', marginBottom: 6, maxWidth: '80%' },
  chatUser: { color: '#FFB300', fontWeight: 'bold', fontSize: 12, marginBottom: 2 },
  chatMsg: { color: '#FFF', fontSize: 14 },
  bottomBar: { position: 'absolute', bottom: 20, left: 10, right: 10, flexDirection: 'row', alignItems: 'center', zIndex: 10 },
  chatInput: { flex: 1, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 20, paddingHorizontal: 15, paddingVertical: 8, color: '#FFF', marginRight: 10 },
  sendBtn: { backgroundColor: '#673AB7', padding: 10, borderRadius: 20, marginRight: 10 },
  controlBtn: { backgroundColor: 'rgba(0,0,0,0.6)', padding: 10, borderRadius: 20, marginRight: 10 },
  btnDisabled: { backgroundColor: '#D32F2F' },
  waitlistBtn: { backgroundColor: '#FFB300', padding: 10, borderRadius: 20 },
  badge: { position: 'absolute', top: -5, right: -5, backgroundColor: 'red', width: 18, height: 18, borderRadius: 9, justifyContent: 'center', alignItems: 'center' },
  badgeText: { color: '#FFF', fontSize: 10, fontWeight: 'bold' },
  giftAnim: { position: 'absolute', top: '40%', alignSelf: 'center', alignItems: 'center', zIndex: 20 },
  giftText: { color: '#FFB300', fontWeight: 'bold', fontSize: 18, marginTop: 5, textShadowColor: 'black', textShadowRadius: 2 },
  modalBg: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#FFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, maxHeight: '60%' },
  modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15, color: '#000' },
  waitlistItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderColor: '#EEE' },
  waitlistName: { fontWeight: 'bold', color: '#000', fontSize: 16 },
  waitlistDetail: { color: '#666', fontSize: 12 },
  actionSmallBtn: { padding: 8, borderRadius: 20 },
  closeModalBtn: { marginTop: 20, padding: 15, backgroundColor: '#EEE', borderRadius: 10, alignItems: 'center' },
  closeModalText: { fontWeight: 'bold', color: '#333' },
});