import { StyleSheet } from 'react-native';
const OTPStyles = StyleSheet.create({
  Cantainer: {
    flex: 1,
     backgroundColor: '#372643',
  },
  backIcon: {
    width: 20,
    height: 20,
    marginLeft: 20,
    tintColor: 'white',
    marginVertical: 12,
  },
  lineCantainer: {
    flexDirection: 'row',
  },
  orText: {
    marginVertical: 10,
    fontSize: 18,
    color: '#f5eeeeff',
  },
  VerfiyText: {
    fontSize: 23,
    fontWeight: '400',
    color: 'white',
    marginLeft: 80,
  },
  headContiner: {
    marginTop: 10,
    flexDirection: 'row',
    alignContent: 'space-between',
    alignItems: 'center',
  },
  lineStyle: {
    marginTop: 10,
    height: 2,
    width: '100%',
    backgroundColor: '#ccc',
    marginRight: 12,
  },
  setnMessaheStore: {
    marginTop: 99,
    marginLeft: 10,
  },
  sentMessageSyle: {
    fontSize: 24,
    fontWeight: '400',
    color: 'white',
    textAlign: 'center',
    marginHorizontal: 10,
  },
  highlightNumber: {
    color: '#FFD700',
    fontWeight: 'bold',
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    marginBottom: 30,
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    // alignItems: 'center',
  },
  boxInput: {
    marginTop: 35,
    width: 50,
    height: 50,
    borderWidth: 2,
    borderColor: 'white',
    borderRadius: 10,
    marginHorizontal: 8,
    fontSize: 24,
    textAlign: 'center',
    color: '#000',
    backgroundColor: '#fff8d6',
  },
  verifyButton: {
    backgroundColor: '#FFD700',
    paddingVertical: 12,
    maginVertical: 15,
    borderRadius: 15,
    width: '92%',
    alignItems: 'center',
    marginTop: 40,
    marginLeft: 15,
  },
  verifyButtonText: {
    color: 'black',
    fontSize: 16,
    fontWeight: '600',
  },
  timerText: {
    marginTop: 40,
    color: 'white',
    marginLeft: 85,
  },
  resendButton: {
    paddingVertical: 12,
    marginVertical: 15,
    borderRadius: 15,
    alignItems: 'center',
    marginTop: 10,
  },
  resendText: {
    marginTop: 20,
    color: 'white',
    fontWeight: 'bold',
  },
  line1: {
    marginTop: 23,
    height: 2,
    width: '45%',
    backgroundColor: '#ccc',
    marginRight: 12,
  },
  line2: {
    marginTop: 23,
    height: 2,
    width: '45%',
    backgroundColor: '#ccc',
    marginLeft: 10,
  },
  truecallerIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  truecallerText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#000',
  },
  truecallerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f1f1',
    borderRadius: 15,
    paddingVertical: 12,
    paddingHorizontal: 15,
    width: '90%',
    justifyContent: 'center',
    marginTop: 15,
    marginLeft: 18,
  },
});

export default OTPStyles;
