import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#372643',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 30,
    alignItems: 'center',
  },
  backButton: {
    position: 'absolute',
    left: 20,
    top: 15,
    zIndex: 10,
    padding: 5,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 10,
  },
  logo: {
    width: 80,
    height: 80,
    marginBottom: 10,
  },
  brandName: {
    color: '#FFD700', // Gold color for brand
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 1,
  },
  card: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 25,
    paddingTop: 30,
    alignItems: 'center',
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: '#333',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 20,
    width: '90%',
  },
  formContainer: {
    width: '100%',
    alignItems: 'center',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    marginBottom: 20,
    height: 55,
    backgroundColor: '#F9F9F9',
    width: '100%',
  },
  countryContainer: {
    borderRightWidth: 1,
    borderRightColor: '#E0E0E0',
    paddingHorizontal: 10,
    height: '100%',
    justifyContent: 'center',
  },
  phoneInput: {
    flex: 1,
    paddingHorizontal: 15,
    fontSize: 16,
    color: '#000',
    height: '100%',
  },
  primaryButton: {
    backgroundColor: '#F59E0B', // Amber/Yellow accent
    width: '100%',
    height: 55,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    marginTop: 10,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 20,
  },
  otpBox: {
    width: 45,
    height: 50,
    borderWidth: 1,
    borderColor: '#CCC',
    borderRadius: 8,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    backgroundColor: '#F9F9F9',
  },
  otpBoxFilled: {
    borderColor: '#372643',
    backgroundColor: '#F3E8FF',
  },
  timerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 25,
  },
  timerText: {
    fontSize: 13,
    color: '#666',
  },
  timerBold: {
    fontWeight: '700',
    color: '#372643',
  },
  resendText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#F59E0B',
  },
  changeNumberText: {
    fontSize: 13,
    color: '#372643',
    textDecorationLine: 'underline',
  },
  footerContainer: {
    marginTop: 'auto',
    marginBottom: 20,
    width: '90%',
  },
  footerNote: {
    fontSize: 12,
    color: '#999',
    textAlign: 'center',
    lineHeight: 18,
  },
  linkText: {
    color: '#F59E0B', // Matching Gold/Amber accent
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
});