import { StyleSheet } from 'react-native';

// -------------------- STYLES --------------------
const RegistrationStyle = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f6f3f8' },
  stepperWrap: { paddingHorizontal: 12, paddingTop: 14 },
  stepRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6 },
  stepDot: {
    width: 25,
    height: 25,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e8dff7',
  },
  stepDotActive: { backgroundColor: '#5b2b84', borderColor: '#5b2b84' },
  stepDotDone: { backgroundColor: '#efe6fb', borderColor: '#5b2b84' },
  stepDotInactive: { backgroundColor: '#fff', borderColor: '#eee' },
  stepDotTextActive: { color: '#fff', fontWeight: '700' },
  stepDotTextDone: { color: '#5b2b84', fontWeight: '700' },
  stepDotTextInactive: { color: '#bbb' },
  connector: { height: 2, borderRadius: 2, marginHorizontal: 1 },

  whitePanel: {
    margin: 12,
    borderRadius: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#f1e9f8',
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 3,
  },
  panelContent: { padding: 18 },
  input: {
    borderWidth: 1,
    borderColor: '#e6dff4',
    borderRadius: 10,
    padding: 12,
    backgroundColor: '#fff',
  },
  radioRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 8 },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d9cee8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#5b2b84',
  },
  radioActive: { borderColor: '#5b2b84' },
  radioText: { fontSize: 14 },
  langBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e6dff4',
    marginBottom: 10,
    marginRight: 8,
    backgroundColor: '#fff',
  },
  langBtnActive: { backgroundColor: '#5b2b84', borderColor: '#5b2b84' },
  langBtnText: { color: '#333' },
  langBtnTextActive: { color: '#fff', fontWeight: '700' },
  addBtn: {
    backgroundColor: '#5b2b84',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 8,
    marginLeft: 8,
  },
  skillTag: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#efe6fb',
    borderRadius: 16,
    marginRight: 8,
    marginTop: 8,
  },
  skillRemove: { backgroundColor: '#9a5bb7', borderRadius: 10, padding: 4 },
  pickerWrap: {
    borderWidth: 1,
    borderColor: '#e6dff4',
    borderRadius: 8,
    overflow: 'hidden',
  },
  profilePreview: { marginTop: 12, width: 150, height: 150, borderRadius: 8 },
  thankTitle: {
    fontSize: 34,
    fontWeight: '900',
    color: '#2b2b2b',
    marginBottom: 12,
  },
  tokenPanel: {
    backgroundColor: '#5b2b84',
    padding: 14,
    borderRadius: 8,
    marginTop: 12,
    alignItems: 'center',
  },
  buttonRow: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  prevBtn: {
    minWidth: 120,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#b98b46',
    alignItems: 'center',
    justifyContent: 'center',
  },
  prevText: { color: '#5b2b84', fontWeight: '700' },
  nextBtn: {
    minWidth: 120,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#5b2b84',
    borderWidth: 2,
    borderColor: '#b98b46',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextText: { color: '#fff', fontWeight: '800' },

  // 📱 Phone selection row
  phoneRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 25,
  },
  phoneOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 30,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ccc',
    backgroundColor: '#fff',
  },
  phoneOptionSelected: {
    borderColor: '#5b2b84',
    backgroundColor: '#f3e8ff',
  },

  radioOuterSelected: {
    borderColor: '#5b2b84',
  },

  phoneLabel: {
    color: '#111',
    fontSize: 16,
  },

  // ==============step:5 styles Skills =========================
  stepContent: {
    marginTop: 10,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111',
    marginBottom: 15,
  },
  labelProfile: {
    left: 65,
    marginTop: -20,
    fontSize: 18,
    fontWeight: '500',
    color: '#111',
    marginBottom: 10,
  },
  //=====================Skill grid cantainer ==============================
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  skillButton: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
    backgroundColor: '#fff',
  },
  skillButtonSelected: {
    borderColor: '#5b2b84',
    backgroundColor: '#f3e8ff',
  },
  skillText: {
    fontSize: 15,
    color: '#333',
    // textAlign: 'center',
    fontWeight: '400',
    marginLeft: 20,
  },
  skillTextSelected: {
    color: '#5b2b84',
    fontWeight: '700',
  },
  symbol: {
    fontWeight: 'bold',
    marginRight: 6,
    left: 10,
  },
  profileCantainer: {
    width: 145,
    height: 145,
    borderWidth: 5,
    borderRadius: 120,
    borderColor: 'black',
    top: 20,
    left: 90,
  },
  ProfileImage: {
    width: 110,
    height: 110,
    left: 14,
    top: 10,
  },
  camera: {
    width: 22,
    height: 22,
    top: 5,
    left: 4,
  },
  cameraCantainer: {
    width: 35,
    height: 35,
    borderWidth: 2,
    borderRadius: 120,
    borderColor: 'lightgrey',
    backgroundColor: 'lightgrey',
    left: 195,
    bottom: 20,
  },
  // ===========================

  profileContainer: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 3,
    borderColor: '#000',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
  },

  profileImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },

  cameraContainer: {
    position: 'absolute',
    bottom: 5,
    right: 105,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 5,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 1,
  },

  cameraIcon: {
    width: 22,
    height: 22,
    tintColor: '#000',
  },
});

export default RegistrationStyle;
